<a href="https://colab.research.google.com/github/priyankak17/Deep-Learning-using-PyTorch/blob/main/PyTorch_Basics_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PyTorch Fundamentals 




In [36]:
#PyTorch is pre installed in Colab

import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

1.13.1+cu116


In [37]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



#[Tensor fundamentals](https://pytorch.org/docs/stable/torch.html)

Building a scalar tensor using torch.Tensor

In [38]:
scalar = torch.Tensor(7)
scalar

tensor([4.9766e-06, 4.5796e-41, 4.1545e-35, 0.0000e+00, 3.5739e-35, 0.0000e+00,
        4.0058e-35])

In [39]:
scalar.ndim

1

In [40]:
scalar.item

<function Tensor.item>

Building vector tensor

In [41]:
vector = torch.Tensor([7,7])


In [42]:
vector

tensor([7., 7.])

In [43]:
vector.ndim

1

In [44]:
vector.shape

torch.Size([2])

Creating a matrix

In [45]:
MATRIX = torch.tensor([[7 , 8] , [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [46]:
MATRIX.ndim

2

In [47]:
MATRIX[0]

tensor([7, 8])

In [48]:
MATRIX[1]

tensor([ 9, 10])

In [49]:
MATRIX.shape

torch.Size([2, 2])

In [50]:
torch.is_tensor(MATRIX)

True

Building tensor

In [51]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6], [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [52]:
TENSOR.ndim

3

In [53]:
TENSOR.shape

torch.Size([1, 3, 3])

In [54]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

###[Dimensionality in tensor](https://improbable-research.github.io/keanu/docs/tensors/#:~:text=A%20tensor%20with%20one%20dimension,each%20dimension%20describes%20its%20shape%20.)


A tensor with one dimension can be thought of as a vector, a tensor with two dimensions as a matrix and a tensor with three dimensions can be thought of as a cuboid. The number of dimensions a tensor has is called its rank and the length in each dimension describes its shape 



#[Random Tensors](https://pytorch.org/docs/stable/generated/torch.rand.html)

Neural networks start with a tensor built using random numbers and perform computations on them and adjust the weight accordingly to achieve aspired results